### ISSUE TITLE
Unhandled Error: -4071 on Windows 10

### ISSUE THREAD

**Issue by kferrio** [nospaceships/node-net-ping#59]
Related to #47 which has been closed. I provide a near-minimal example to reproduce.

Windows 10 Pro
net-ping 1.2.3 gyp'ed with Visual Studio 2017 Community via `npm i net-ping`.
node 8.11.4

```
const ping = require('net-ping');
const session = ping.createSession();

var myTimer = setInterval(doWork, 1000);

function doWork() {
	var d = new Date();
	session.pingHost("8.8.8.8", (err, target) => {
		var result = 'ok';
		if (err) {
			if (err instanceof ping.RequestTimedOutError) {
				result = 'timeout';
			} else {
				result = 'unknown';
			}
		}
		console.log(`${d.toLocaleString()}\t${target}\t${result}`);
	});
}
```
At no particular time, but typically within an hour, execution terminates with
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: -4071
```
I'm going to wrap the ping in a try/catch (since I need this to keep running) and will update this issue when I know more.

**Comment by kferrio** [comment]
Adding try/catch did not help, perhaps for the reason [here](https://stackoverflow.com/questions/19983348/node-js-throwing-error-and-its-not-being-caught) for async callbacks?

**Comment by kferrio** [comment]
I have not been able to repro this in the last hour, now with multiple instances of the example running concurrently. I'm going to close this and will reopen if I learn more.

**Comment by stephenwvickers** [comment]
@kferrio try calling the close() method on the sessions once you've finished with them. You likely ran out of file handles.

**Comment by kferrio** [comment]
Ah!  Thanks @stephenwvickers.  I was just about to report that I've seen in fail two more times in the last hour.  File handles would explain the "randomness."  I really do want to keep pings going indefinitely, for monitoring. So I'll add some logic to cycle the session.

**Comment by kferrio** [comment]
Unfortunately, calling `close()` on the session after every `pingHost()` did not prevent the -4071 error. In addition, I have now seen one instance of `Assertion failed: !(handle->flags & UV__HANDLE_CLOSING)` in libuv itself at src\win\poll.c, line 475 in function `uv__slow_poll_set()`.  I'm not inclined to learn about the libuv internals, so I may see if I can get the runtimes I need on Debian instead of Windows.

**Comment by stephenwvickers** [comment]
Mm, that's odd. That normally means close() was called twice.

In general, one would create a session once and use it forever, I.e. not keep creating them.

**Comment by kferrio** [comment]
I'm creating one session instance and then at 1-second intervals calling both pingHost (single target) and close() on that single session over and over. 

Thanks for your help!  I'm going to have to leave this for next weekend, at which time I may just run on Debian. I've been away from node for a couple years, and I wonder if Windows support still has some sharp edge cases.  Thanks!

**Comment by stephenwvickers** [comment]
You don't need to call close() if you are using the session over and over. If you create a new session each time then call close() on the unseeded session.

The module is used by a number of long running monitoring systems so you should be okay.

**Comment by kferrio** [comment]
I'm creating just one session, which I use to ping just one host thousands of times. The unhandled exception happens whether I call close() or not. Something is definitely not stable but I'm not sure how to get useful debugging information. If my code runs ten times longer on Debian, I'll conclude this is a Windows-specific issue. Thanks.

**Comment by kferrio** [comment]
Reproduced on a second Windows box, also using the msbuild detected by gyp from Visual Studio 2017 Community.

**Comment by kferrio** [comment]
Same script has been running over three hours on Ubuntu 18.04.1 under WSL. Unfortunately, this might not be a fair comparison; node version is 8.12.0, compared to 8.11.4 on Win10. 

To make a better comparison, I undated Win10 to node 8.12.0. The same script faulted (-4071) in less than 5 minutes.

I'm tagging this with Windows.

**Comment by stephenwvickers** [comment]
Hi @kferrio 

Can you provide a complete and working program which emits the behavior so I can investigate further.

Thanks

Steve

**Comment by kferrio** [comment]
Yes. See the very first post in this issue.

**Comment by stephenwvickers** [comment]
@kferio that program will eventually run out of sockets and crash.

**Comment by kferrio** [comment]
@stephenwvickers Agreed. But consider:

1. Sometimes it crashes after fewer than 100 timer events, other times after 1000+, and always after fewer than 5000.

2. Adding a session.close() in the callback has no discernable effect; it still crashes after a "random" number of calls between 10 and 5000; and

3. It's been running for several days now on Ubuntu (under WSL) with exactly zero crashes. 

I've poked around in the sources a bit. I'm not prepared to point to the cause but I am pretty sure the problem is _not_ in net-ping. But net-ping does appear to be a very reliable way to exercise the behavior and show platform dependence.

Thanks.

**Comment by kferrio** [comment]
I forgot to mention... on both Win10 and WSL-Ubuntu, I am using prebuilt binaries from nodejs.org. I am not building node from source, nor am I using any third-party builds, e.g. whatever is in the Ubuntu apt repos.

**Comment by kferrio** [comment]
I have built node-8.12.0 from source, using the VS 2017 build tools.  The build is clean but 15 tests fail, including several with the same error that prompted this issue -- an unhandled error @line 183 of events.js:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^
```
This proves nothing but does suggest that something about event.js may not be entirely stable on Win10 at this time.

I've started a run of my demo script, share what I learn and then close this issue if I have not found evidence implicating net-ping.

Thanks!

**Comment by kferrio** [comment]
My script has executed 8,000 pings under the built-from-source node 8.12.0 on Win10 and is still going.  The longest run with the "official" 8.12.0 build for Win10 x64 was less than 5,000, with an average of 1000 and a standard deviation of 600 with a strongly bimodal distribution on an otherwise mostly idle box.  So while 8,000 proves nothing, it seems statistically significant. It's hard to say. Whether the root cause is handle exhaustion or a race condition, this definite;y exonerates net-ping. Closing issue.
