### ISSUE TITLE
Symbol not found in node_modules/raw-socket/build/Release/raw.node

### ISSUE THREAD

**Issue by zmczxn** [nospaceships/node-net-ping#63]
when I use net-ping in a electron project, I get a 'Symbol not found' error & crash. I use 'npm install net-ping' and the code 'const ping = require('net-ping')'. Do you have any ideas about the error?
More information:
node: v10.12.0
node-gyp: v3.8.0
npm: 6.4.1
electron: 4.0.1
mac os 
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
    Referenced from: /Users/useName/WorkSpace/projectName/node_modules/raw-socket/build/Release/raw.node
    Expected in: flat namespace

**Comment by stephenwvickers** [comment]
Hi @zmczxn,

I've never used electron so I have no idea how it handles Node.js addon modules which use C++ code.

I see there may be some extra steps required here:

https://electronjs.org/docs/tutorial/using-native-node-modules

Steve

**Comment by zmczxn** [comment]
thank you very much for advice, electron-rebuild works for this error.
