### ISSUE TITLE
Documentation could be clearer

### ISSUE THREAD

**Issue by multicron** [nospaceships/node-net-ping#66]
If one instantiates several Session objects, the ping replies generated by the various Session objects are all confused with one another, because SessionId is set to process.pid % 65536.  For this reason, using separate Session instances for pinging various hosts doesn't work as expected.

It would have been helpful for my understanding to realize that all my pinging should be done with a single Session object.  I'm not sure under what circumstances one might use multiple Session objects in a useful way (except that the IPv6 pings require a separate Session instance).

**Comment by stephenwvickers** [comment]
Hi @multicron 

Sessions are used to ping multiple hosts at once, and when you create a session you are not required to provide any IP address, only if you require IPv4 or IPv6,  This is stated in the `createSession()` methods documentation:

> Seperate instances of the Session class must be created for IPv4 and IPv6.

Then, when using ping or trace-route, you are required then to provide an IP address.  That is, you use a single session to communicate with multiple hosts.

You are not required to use a single session for all pings though, and that is why you can provide your own session ID to ensure a session can identify it's own packets, this is documented in the `createSession` method.
