### ISSUE TITLE
Output's body on Windows does not necessary contains 'ms' words

### ISSUE THREAD

**Issue by AdamAffou** [nospaceships/node-net-ping#70]
Hi,

When you process the output's body on Windows in the lib/parser/win.js, you're looking for 'ms' keyword. But the response does not necssary contains this word. Such as : 

`[ 'octets=32', 'temps=1', 'TTL=128']`

I edited the code and it works fine with line 51 replaced by : 
`  return kvp.indexOf('temps') >= 0;`
instead of : 
`  return kvp.indexOf('ms') >= 0;`

Regards.

**Comment by stephenwvickers** [comment]
Was this I tended for a different repo?

We don't have that file.

**Comment by AdamAffou** [comment]
Hi,

Yes sorry, my bad. I close it.
