### ISSUE TITLE
Permission denied to create raw sockets in Linux ubuntu

### ISSUE THREAD

**Issue by mawandahenry** [nospaceships/node-net-ping#75]
Hey, could someone help me resolve this issue. Net-ping crashes with the error "this.wrap = new raw.SocketWrap (Error: Operation not permitted)".
Thanks

**Comment by vendornltd** [comment]
This module uses the raw-socket module to create raw sockets and perform the ping, see the following note:

https://www.npmjs.com/package/raw-socket#raw-socket-behaviour
